# Generated by Django 4.0.4 on 2023-04-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='view_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hamlet',
            name='view_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='view_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='view_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='view_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
