# Generated by Django 4.0.4 on 2023-04-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_district_view_id_hamlet_view_id_region_view_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='dictionary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hamlet',
            name='dictionary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='dictionary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='dictionary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='dictionary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
