# Generated by Django 4.0.4 on 2022-04-27 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('flag', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('verify', models.IntegerField(default=0)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Menu',
                'db_table': 'cb_menus',
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_id', models.IntegerField(default=0)),
                ('title', models.TextField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.menu')),
            ],
            options={
                'verbose_name_plural': 'Sub Menus',
                'db_table': 'cb_sub_menus',
            },
        ),
        migrations.CreateModel(
            name='MenuSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(default='whatsapp', max_length=100)),
                ('values', models.TextField(blank=True, null=True)),
                ('active', models.IntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.menu')),
            ],
            options={
                'verbose_name_plural': 'Menu Sessions',
                'db_table': 'cb_menu_sessions',
            },
        ),
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='link', to='whatsapp.menu')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='whatsapp.menu')),
                ('sub_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='whatsapp.submenu')),
            ],
            options={
                'verbose_name_plural': 'Menu Links',
                'db_table': 'cb_menu_links',
            },
        ),
    ]
