# Generated by Django 4.0.4 on 2022-04-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusession',
            name='sent',
            field=models.IntegerField(default=0),
        ),
    ]
