# Generated by Django 4.0.4 on 2022-04-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_menusession_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='view_id',
            field=models.CharField(max_length=10),
        ),
    ]
