# Generated by Django 4.0.4 on 2022-06-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_alter_submenu_view_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='post_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
