# Generated by Django 4.0.4 on 2023-01-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_menu_post_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='verify',
            new_name='pull',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='post_url',
        ),
        migrations.AddField(
            model_name='menu',
            name='action',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
