# Generated by Django 4.0.4 on 2023-01-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_rename_verify_menu_pull_remove_menu_post_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menusession',
            old_name='message_id',
            new_name='flag',
        ),
    ]
