# Generated by Django 4.0.4 on 2023-02-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='action_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
