# Generated by Django 4.0.4 on 2023-02-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_thread_action_url_alter_thread_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='action',
            field=models.CharField(blank=True, choices=[('PUSH', 'PUSH'), ('CREATE', 'CREATE')], max_length=20, null=True),
        ),
    ]
