# Generated by Django 4.0.4 on 2023-02-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_alter_thread_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='step',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
