# Generated by Django 4.0.4 on 2023-04-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0004_thread_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='url',
            new_name='pull_url',
        ),
    ]
