# Generated by Django 4.0.4 on 2023-04-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0005_rename_url_thread_pull_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='pull',
            new_name='verify',
        ),
    ]
