# Generated by Django 4.0.4 on 2023-04-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0006_rename_pull_thread_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='verify_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
